services:
  web:
    build: .
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 THE24_Website.wsgi:application
    entrypoint: ["/app/entrypoint.sh"]
    user: "1000:1000"  # This is myuser's UID and GID
    volumes:
      - .:/app
      - ./logs:/app/logs  # Ensure the logs directory is mounted
      - ./media:/app/media  # Media files volume
      - ./staticfiles:/app/staticfiles        # Static files volume
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PWD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf   # Correct path to nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf   # Correct path to default.conf
      - ./staticfiles:/app/staticfiles   # Using shared static volume
      - ./media:/app/media          # Using shared media volume
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/static/"]
      interval: 60s
      timeout: 10s
      retries: 5
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:
  staticfiles:
  media:

networks:
  app-network:
    driver: bridge
