services:
  web:
    build: .
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 --reload THE24_Website.wsgi:application
    entrypoint: ["/app/entrypoint.sh"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PWD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
  nginx:
    image: nginx:latest
    volumes:
      - ./staticfiles:/app/staticfiles  # Mount the static files director
      - ./media:/app/media  # Mount the media files directory
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Nginx config
    ports:
      - "80:80"  # Expose Nginx on port 80
    depends_on:
      - web  # Wait for the web (Gunicorn/Django) service to be ready
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  redis_data:
