services:
  web:
    build: .
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 THE24_Website.wsgi:application
    entrypoint: ["/app/entrypoint.sh"]
    volumes:
      - .:/app  # Good for development
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    healthcheck:
      test: ["CMD", "-f", "http://localhost:8000" ]
      interval: 30s
      timeout: 10s
      retries: 5
    
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PWD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5
    
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data # Persist Redis data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
  
volumes:
  postgres_data:
  redis_data: